//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResturantProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ResturantProjectEntities : DbContext
    {
        public ResturantProjectEntities()
            : base("name=ResturantProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_CATEGORY> TBL_CATEGORY { get; set; }
        public virtual DbSet<TBL_ITEMLIST> TBL_ITEMLIST { get; set; }
        public virtual DbSet<Roles> RolesSet { get; set; }
        public virtual DbSet<Users> UsersSet { get; set; }
    
        public virtual ObjectResult<string> spGetCategories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spGetCategories");
        }
    
        public virtual ObjectResult<TBL_ITEMLIST> spGetStarters()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_ITEMLIST>("spGetStarters");
        }
    
        public virtual ObjectResult<TBL_ITEMLIST> spGetStarters(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_ITEMLIST>("spGetStarters", mergeOption);
        }
    
        public virtual ObjectResult<TBL_ITEMLIST> spGetDesserts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_ITEMLIST>("spGetDesserts");
        }
    
        public virtual ObjectResult<TBL_ITEMLIST> spGetDesserts(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_ITEMLIST>("spGetDesserts", mergeOption);
        }
    
        public virtual ObjectResult<TBL_ITEMLIST> spGetMainCourse()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_ITEMLIST>("spGetMainCourse");
        }
    
        public virtual ObjectResult<TBL_ITEMLIST> spGetMainCourse(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_ITEMLIST>("spGetMainCourse", mergeOption);
        }
    }
}
