//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResturantProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ITEMLIST
    {
        public int ID { get; set; }
        public Nullable<int> CATEID { get; set; }
        public string ITEMNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string TYPE { get; set; }
        public Nullable<bool> ENABLED { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ImagePath { get; set; }
        public byte[] MenuImage { get; set; }
        public string CategoryName { get; set; }
    }
}
